	Line   Col    Type            Value                     Text                     
	1      1      TInt            1                         1                        
	1      3      TPlus           +                         +                        
	1      5      TInt            23                        23                       
	1      8      TPlus           +                         +                        
	1      10     TDouble         1                         1.0                      
	1      14     TMinus          -                         -                        
	1      16     TInt            312                       312                      
	1      20     TMul            *                         *                        
	1      22     TOp             (                         (                        
	1      23     TInt            1                         1                        
	1      25     TMul            *                         *                        
	1      27     TInt            2                         2                        
	1      28     TCp             )                         )                        
	2      1      TInt            1                         1                        
	2      2      TPlus           +                         +                        
	2      3      TInt            23                        23                       
	2      5      TPlus           +                         +                        
	2      6      TDouble         1                         1.0                      
	2      9      TMinus          -                         -                        
	2      10     TInt            312                       312                      
	2      13     TMul            *                         *                        
	2      14     TOp             (                         (                        
	2      15     TInt            1                         1                        
	2      16     TMul            *                         *                        
	2      17     TInt            2                         2                        
	2      18     TCp             )                         )                        
	3      1      TInt            1                         1                        
	3      2      TShare          /                         /                        
	3      3      TInt            2                         2                        
	3      4      TShare          /                         /                        
	3      5      TDouble         1                         1.0                      
