	Line   Col    Type            Value                     Text                     
	1      1      TKeyword        var                       var                      
	2      5      TId             b                         b                        
	2      7      TId             integer                   integer                  
	3      5      TId             _a_                       _a_                      
	3      9      TId             real                      real                     
	4      1      TKeyword        begin                     begin                    
	5      5      TId             _a_                       _a_                      
	5      10     THex            0                         $0000000000              
	6      5      TId             print                     print                    
	6      11     TId             _a_                       _a_                      
	7      1      TKeyword        end                       end                      
	7      4      TPoint          .                         .                        
