	Line   Col    Type            Value                     Text                     
	1      1      TKeyword        var                       var                      
	2      5      TId             b                         b                        
	2      6      TColom          :                         :                        
	2      8      TId             integer                   integer                  
	2      15     TSemicolom      ;                         ;                        
	3      5      TId             _a_                       _a_                      
	3      8      TColom          :                         :                        
	3      10     TId             real                      real                     
	3      14     TSemicolom      ;                         ;                        
	4      1      TKeyword        begin                     begin                    
	5      5      TId             b                         b                        
	5      7      TEq             =                         =                        
	5      9      TInt            100                       100                      
	5      12     TSemicolom      ;                         ;                        
	6      5      TId             _a_                       _a_                      
	6      8      TAssign         :=                        :=                       
	6      10     THex            0                         $0000000000              
	6      21     TSemicolom      ;                         ;                        
	7      5      TId             print                     print                    
	7      10     TOp             (                         (                        
	7      11     TId             _a_                       _a_                      
	7      14     TCp             )                         )                        
	7      15     TSemicolom      ;                         ;                        
	8      1      TKeyword        end                       end                      
	8      4      TPoint          .                         .                        
