	Line   Col    Type            Value                     Text                     
	1      1      TInt            1                         1                        
	1      2      TRange          ..                        ..                       
	1      4      TInt            100                       100                      
	2      1      TMinus          -                         -                        
	2      2      TInt            100                       100                      
	2      5      TRange          ..                        ..                       
	2      7      TPlus           +                         +                        
	2      8      TInt            100                       100                      
	3      1      TRange          ..                        ..                       
	3      3      TRange          ..                        ..                       
	3      5      TRange          ..                        ..                       
	3      7      TPoint          .                         .                        
	4      1      TId             abx                       abx                      
	4      4      TRange          ..                        ..                       
	4      6      TId             vfd                       vfd                      
	5      1      TId             a                         a                        
	5      2      TRange          ..                        ..                       
	5      4      TId             b                         b                        
Ошибка в (6, 3): invalid digit found in string => Error in format of Integer
